scss_files: 'scss/*.scss'

linters:
  ColorVariable:
    enabled: false

  SingleLinePerSelector:
    enabled: false

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  SelectorDepth:
    enabled: false

  NestingDepth:
    enabled: false

  QualifyingElement:
    enabled: false
